version: "3.9"
services:
   mongodb:
     image: "mongo:latest"
     hostname: mongodb
     ports: 
       - "27017:27017"
     volumes:
       - './data:/data/db'
    nodejs:
     build: .
     image : "demo-service"
     ports:
       - "8000:3000"
     depends_on:
       - mongodb
     environment:
       MONGODB_URI: mongodb://mongodb:27017/demo
       PORT : 3000
